name       : python-libevdev
version    : 0.9
release    : 2
source     :
    - https://gitlab.freedesktop.org/libevdev/python-libevdev/-/archive/0.9/python-libevdev-0.9.tar.gz : 16d0616a4040bdf37f6a27fc2d2e685574994ebf91818f24dfe389533ef9558d
license    : MIT
component  : programming.python
homepage   : https://gitlab.freedesktop.org/libevdev/python-libevdev/
summary    : A Python wrapper around libevdev
description: |
    This project is a Python wrapper around libevdev, taking advantage of libevdev's advanced event handling.
builddeps  :
    - pkgconfig(libevdev)
rundeps    :
    - libevdev
build      : |
    %python3_setup
install    : |
    %python3_install
